### ISSUE TITLE
Add error timeout on loading spinner

### ISSUE THREAD

**Issue by f-f** [KSF-Media/affresco#6]
Currently if some error happens during the async execution tied to the loading spinner, it just stays there forever.

This is not nice, and we should add a timeout on the spinner, so if it has been on for e.g. more than 30 secs we stop it and display an error.

**Comment by zudov** [comment]
I'd like to point out that if the loading spinner stays forever it is a bug.

Having a spinner timeout and appropriate message is of course needed (since bugs happen and we don't want users to wait cluelessly for hours), but if it ever gets displayed we should treat it as a bug. (e.g. "The async action went into infinite looping, didn't timeout itself correctly, launched the rockets without opening the silo." not "The async action was just taking too long").

**Comment by zudov** [comment]
BTW, there's another spinner bug that I'm keeping in mind, but haven't told anyone :D

When there are several overlapping async actions, something like that can happen:

1. Action A starts (spinner is turned on)
2. Action B starts (spinner is turned on)
3. Action B ends (spinner is turned off)
4. Action A ends (spinner is turned off)

Thus, during steps (3) and (4) the spinner won't be shown, even though it should be. The fix isn't hard, instead of a boolean loader switch there should be a counter that increments/decrements when the async actions start/stop. I'll either fix it along with this issue, or open another one if it doesn't fit well.
